name: Audira
options:
  bundleIdPrefix: com.jacksonmaroon
configs:
  Debug: debug
  Release: release
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.9
targets:
  Audira:
    type: application
    platform: macOS
    sources:
      - path: Sources/Audira
      - path: Audira/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jacksonmaroon.Audira
        PRODUCT_NAME: Audira
        INFOPLIST_FILE: Audira/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
