name: AikoCanary
options:
  bundleIdPrefix: com.jacksonmaroon
configs:
  Debug: debug
  Release: release
settings:
  base:
    MACOSX_DEPLOYMENT_TARGET: 13.0
    SWIFT_VERSION: 5.9
targets:
  AikoCanary:
    type: application
    platform: macOS
    sources:
      - path: Sources/AikoCanary
      - path: AikoCanary/Assets.xcassets
        buildPhase: resources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jacksonmaroon.AikoCanary
        PRODUCT_NAME: Audira
        INFOPLIST_FILE: AikoCanary/Info.plist
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
